---
kind: Namespace
apiVersion: v1
metadata:
  name: kubetail
---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    k8s-app: kubetail
  name: kubetail
  namespace: kubetail
data:
  config.yaml: |
    auth-mode: cluster
    csrf:
      secret: REPLACEME
    session:
      secret: REPLACEME
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: kubetail
  name: kubetail
  namespace: kubetail
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    k8s-app: kubetail
  name: kubetail
  namespace: kubetail
rules:
  - apiGroups: ["", "apps", "batch"]
    resources: ["cronjobs", "daemonsets", "deployments", "jobs", "namespaces", "nodes", "pods", "pods/log", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubetail
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubetail
subjects:
  - kind: ServiceAccount
    name: kubetail
    namespace: kubetail
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: kubetail
  name: kubetail
  namespace: kubetail
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kubetail
  template:
    metadata:
      labels:
        k8s-app: kubetail
    spec:
      serviceAccountName: kubetail
      containers:
        - name: kubetail
          image: kubetail/kubetail:0.1.0
          ports:
            - containerPort: 4000
              protocol: TCP
          args:
            - "-c"
            - "/etc/kubetail/config.yaml"
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 4000
            initialDelaySeconds: 30
            timeoutSeconds: 30
          volumeMounts:
            - name: config
              mountPath: /etc/kubetail
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: kubetail
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kubetail
  name: kubetail
  namespace: kubetail
spec:
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    k8s-app: kubetail
---
